Repository similarweb/kubectl-ipick, pull requests merged in 2020-07, with the labels that each got.

#5 Order ci files
  .github/workflows/security.yml
  .github/workflows/test.yml
Labels: enhancement, lgtm

#6 Ignore system and add windows binary
  .goreleaser.yml
Labels: enhancement, lgtm

#7 Doc/add readme file
  CONTRIBUTING.md
  README.md
  cmd/root.go
  docs/images/demo.gif
Labels: lgtm

#8 Fix selection bug
  pkg/interactive/interactive.go
  pkg/interactive/resources.go
  pkg/interactive/resources_test.go
Labels: bug, lgtm

#10 Add version command
  .goreleaser.yml
  README.md
  cmd/version.go
Labels: lgtm

#12 Add the option of Alias to docs.
  README.md
Labels: documentation, lgtm

#13 Change README.md file, change printer table name + fix command flags …
  README.md
  cmd/root.go
  command/command.go
  command/command_test.go
  pkg/interactive/contexts.go
  pkg/interactive/contexts_test.go
  pkg/interactive/interactive.go
  pkg/interactive/resources.go
  pkg/interactive/resources_test.go
Labels: documentation, enhancement

#15 change plugin name
  .goreleaser.yml
  Makefile
  README.md
  cmd/root.go
  cmd/version.go
  command/command.go
  go.mod
  go.sum
  kubectl-ipick.go
  pkg/interactive/interactive_test.go
  pkg/interactive/resources.go
  pkg/interactive/resources_test.go
  pkg/ipick/contexts.go
  pkg/ipick/contexts_test.go
  pkg/ipick/ipick.go
  pkg/ipick/ipick_test.go
  pkg/ipick/query.go
  pkg/ipick/query_test.go
  pkg/ipick/resources.go
  pkg/ipick/resources_test.go
  pkg/ipick/testutils/invalid-path-kubeconfig
  pkg/ipick/testutils/kubeconfig
  printers/printers_test.go
  printers/table.go
  prompt/prompt.go
Labels: enhancement, lgtm

#18 Add krew as part of the git action
  .github/workflows/release.yaml
  .krew.yaml
  README.md
Labels: documentation, enhancement

#19 Logging and error messages improvements
  cmd/root.go
  command/command.go
  pkg/ipick/contexts.go
  pkg/ipick/ipick.go
  prompt/prompt.go
Labels: enhancement

#20 Fix switch context command
  pkg/ipick/contexts.go
Labels: bug

#21 fix .krew indentation
  .krew.yaml
Labels: enhancement

#24 fix .krew template
  .krew.yaml
Labels: bug

#25 add more args validation
  cmd/root.go
Labels: bug

#26 fix donwload links
  README.md
Labels: bug, documentation
